# Generated by Django 5.1 on 2024-08-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discounts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='products',
            field=models.ManyToManyField(related_name='discounts', to='products.product'),
        ),
    ]
